local color = {}
local palette = {colors = {}}
palette.__index = palette

local mt = {
	__add = function (c1,c2)
		return color.new(c1[1]+c2[1],c1[2]+c2[2],c1[3]+c2[3])
	end,
	__sub = function (c1,c2)
		return color.new(c1[1]-c2[1],c1[2]-c2[2],c1[3]-c2[3])
	end,
	__mul = function (c1,c2)
		return color.new(c1[1]*c2[1],c1[2]*c2[2],c1[3]*c2[3])
	end,
	__div = function (c1,c2)
		return color.new(c1[1]/c2[1],c1[2]/c2[2],c1[3]/c2[3])
	end,
	__mod = function (c1,c2)
		return color.new(c1[1]%c2[1],c1[2]%c2[2],c1[3]%c2[3])
	end,
	__pow = function (c1,c2)
		return color.new(c1[1]^c2[1],c1[2]^c2[2],c1[3]^c2[3])
	end,
	__unm = function (c1)
		return color.new(-c1[1],-c1[2],-c1[2])
	end,
	__tostring = function(c)
		local name = c.name or ""
		if name ~= "" then
			name = name .. ": "
		end
		return name .. "("..c[1]..","..c[2]..","..c[3]..",".. (c[4] or "1") ..")"
	end,
	__eq = function (c1,c2)
		return (c1[1]==c2[1] and c1[2]==c2[2] and c1[3]==c2[3])
	end,
	__lt = function (c1,c2)
		return (c1[1]<c2[1] and c1[2]<c2[2] and c1[3]<c2[3])
	end,
	__le = function (c1,c2)
		return (c1[1]<=c2[1] and c1[2]<=c2[2] and c1[3]<=c2[3])
	end
}

local v3 = false
local min = math.min
local max = math.max
local abs = math.abs

function color.hsl(h, s, l, a)
	if s<=0 then return l,l,l end
	h, s, l = h/360*6, s/100, l/100
	local c = (1-math.abs(2*l-1))*s
	local x = (1-math.abs(h%2-1))*c
	local m,r,b,g = (l-.5*c), 0,0,0
	if h < 1     then r,b,g = c,x,0
	elseif h < 2 then r,b,g = x,c,0
	elseif h < 3 then r,b,g = 0,c,x
	elseif h < 4 then r,b,g = 0,x,c
	elseif h < 5 then r,b,g = x,0,c
	else              r,b,g = c,0,x
	end return (r+m), (g+m), (b+m), a or 1
end

function color.hsv(h, s, v)
    local k1 = v*(1-s)
    local k2 = v - k1
    local r = min (max (3*abs (((h      )/180)%2-1)-1, 0), 1)
    local g = min (max (3*abs (((h  -120)/180)%2-1)-1, 0), 1)
    local b = min (max (3*abs (((h  +120)/180)%2-1)-1, 0), 1)
    return k1 + k2 * r, k1 + k2 * g, k1 + k2 * b, 1
end

function color.isLight(r, g, b)
	if type(r) == "string" then
		r, g, b = tonumber(string.sub(r,1,2),16),tonumber(string.sub(r,3,4),16),tonumber(string.sub(r,5,6),16)
	elseif type(r) == "table" then
		r, g, b =  r[1], r[2], r[3]
	end
    return (r + g + b) / 3 >= .5
end

function color.getAverageLightness(r, g, b)
	if type(r) == "string" then
		r, g, b = tonumber(string.sub(r,1,2),16),tonumber(string.sub(r,3,4),16),tonumber(string.sub(r,5,6),16)
	elseif type(r) == "table" then
		r, g, b =  r[1], r[2], r[3]
	end
    return (r + g + b) / 3
end

function color.rgbToHex(r, g, b)
	if type(r) == "string" then
		r, g, b = tonumber(string.sub(r,1,2),16),tonumber(string.sub(r,3,4),16),tonumber(string.sub(r,5,6),16)
	elseif type(r) == "table" then
		r, g, b =  r[1], r[2], r[3]
	end

	r, g, b = love.math.colorToBytes(r,g,b,0)

	local rgb = (r * 0x10000) + (g * 0x100) + b
    return string.format("%06x", rgb)
end

function color.setV3(b)
	v3 = b
end

local function parseColor(r, g, b, a)
	local temp
	if type(r) == "string" then
		if r == "random" then
			if v3 then
				return unpack(color.random())
			else
				return unpack(color.random())
			end
		end
		r = r:gsub("%s",""):gsub("%%","")
		if r:sub(1,4) == "rgba" then
			local sr,sg,sb,sa = r:match("rgba%((%d-),(%d-),(%d-),(%d*%.?%d+)%)")
			r,g,b = love.math.colorFromBytes(tonumber(sr),tonumber(sg),tonumber(sb))
			a = tonumber(sa)
		elseif r:sub(1,4) == "hsla" then
			local sh,ss,sl,sa = r:match("hsla%((%d-),(%d-),(%d-),(%d*%.?%d+)%)")
			r,g,b,a = color.hsl(tonumber(sh), tonumber(ss), tonumber(sl), tonumber(sa))
		elseif r:sub(1,3) == "hsl" then
			local sh,ss,sl = r:match("hsl%((%d-),(%d-),(%d-)%)")
			r,g,b,a = color.hsl(tonumber(sh), tonumber(ss), tonumber(sl))
		elseif r:sub(1,5) == "rgb01" then
			local sr,sg,sb = r:match("rgb01%((%d*%.?%d+),(%d*%.?%d+),(%d*%.?%d+)%)")
			r,g,b = tonumber(sr),tonumber(sg),tonumber(sb)
		elseif r:sub(1,3) == "rgb" then
			local sr,sg,sb = r:match("rgb%((%d-),(%d-),(%d-)%)")
			r,g,b = love.math.colorFromBytes(tonumber(sr),tonumber(sg),tonumber(sb))
		else
			if r:sub(1,1) == "#" then
				r = r:sub(2,-1) 
			end
			if #r == 8 then
				r, g, b, a = tonumber(string.sub(r,1,2),16),tonumber(string.sub(r,3,4),16),tonumber(string.sub(r,5,6),16),tonumber(string.sub(r,7,8),16)
			else
				r, g, b = tonumber(string.sub(r,1,2),16),tonumber(string.sub(r,3,4),16),tonumber(string.sub(r,5,6),16)
			end
			if v3 then
				return love.math.colorFromBytes(r, g, b)
			else
				return love.math.colorFromBytes(r, g, b, a or 255)
			end
		end
	elseif type(r) == "table" then
		if v3 then
			return r[1], r[2], r[3]
		else
			return r[1], r[2], r[3], 1
		end
	end
	if v3 then
		return r, g, b
	else
		return r, g, b, 1
	end
end

function color.newPalette(name)
    local p = {}
    setmetatable(p,palette)
    color[name] = p
    return p
end

function color.getPalette(name)
    return color[name]
end

function color.darken(c, v)
	local currentR,currentG,currentB=c[1],c[2],c[3]
	return color.new((currentR*255) * (1 - v),(currentG*255) * (1 - v),(currentB*255) * (1 - v))
end

function color.lighten(c, v)
	local currentR,currentG,currentB=c[1],c[2],c[3]
	return color.new(currentR*255 + (255 - (currentR*255)) * v,currentG*255 + (255 - (currentG*255)) * v,currentB*255 + (255 - (currentB*255)) * v)
end

function palette.new(r, g, b, a)
	local temp = {parseColor(r, g, b, a)}
	setmetatable(temp, mt)
	return temp
end

function palette:indexColor(name, r, g, b, a)
	local c = palette.new(r, g, b, a)
	self[name] = c
	self[string.lower(name)] = c
	self[string.upper(name)] = c
	self[string.upper(string.sub(name,1,1))..string.lower(string.sub(name,2))] = c
	c.name = name
	table.insert(self.colors, name)
end

function palette:listColors()
	local list = {}
	for i,v in ipairs(self) do
		list[#list+1] = v
	end
	return list
end

-- Allows you to modify an existing color that has been indexed
function palette:reindexColor(name, r, g, b, a)
	local _v3 = v3
	if #self[name] == 3 then
		v3 = true
	end
	local r, g, b, a = parseColor(r, g, b, a)
	self[string.lower(name)][1] = r
	self[string.lower(name)][2] = g
	self[string.lower(name)][3] = b
	if not v3 then
		self[string.lower(name)][4] = a
	end
	v3 = _v3
end

local initD = false
function color.getDefaultPalette()
    local p
	if not color.getPalette("$gui.core.color") then
		p = color.newPalette("$gui.core.color")
    end
    if not initD then
        initD = true
        p:indexColor("WHITE","rgb(255,255,255)")
        p:indexColor("MAROON","rgb(128,20,20)")
        p:indexColor("DARK_RED","rgb(139,20,20)")
        p:indexColor("BROWN","rgb(165,42,42)")
        p:indexColor("FIREBRICK","rgb(178,34,34)")
        p:indexColor("CRIMSON","rgb(220,20,60)")
        p:indexColor("TOMATO","rgb(255,99,71)")
        p:indexColor("CORAL","rgb(255,127,80)")
        p:indexColor("INDIAN_RED","rgb(205,92,92)")
        p:indexColor("LIGHT_CORAL","rgb(240,128,128)")
        p:indexColor("DARK_SALMON","rgb(233,150,122)")
        p:indexColor("SALMON","rgb(250,128,114)")
        p:indexColor("LIGHT_SALMON","rgb(255,160,122)")
        p:indexColor("ORANGE_RED","rgb(255,69,20)")
        p:indexColor("DARK_ORANGE","rgb(255,140,20)")
        p:indexColor("ORANGE","rgb(255,165,20)")
        p:indexColor("GOLD","rgb(255,215,20)")
        p:indexColor("DARK_GOLDEN_ROD","rgb(184,134,11)")
        p:indexColor("GOLDEN_ROD","rgb(218,165,32)")
        p:indexColor("PALE_GOLDEN_ROD","rgb(238,232,170)")
        p:indexColor("DARK_KHAKI","rgb(189,183,107)")
        p:indexColor("KHAKI","rgb(240,230,140)")
        p:indexColor("OLIVE","rgb(128,128,20)")
        p:indexColor("YELLOW_GREEN","rgb(154,205,50)")
        p:indexColor("DARK_OLIVE_GREEN","rgb(85,107,47)")
        p:indexColor("OLIVE_DRAB","rgb(107,142,35)")
        p:indexColor("LAWN_GREEN","rgb(124,252,20)")
        p:indexColor("CHART_REUSE","rgb(127,255,20)")
        p:indexColor("GREEN_YELLOW","rgb(173,255,47)")
        p:indexColor("DARK_GREEN","rgb(20,100,20)")
        p:indexColor("FOREST_GREEN","rgb(34,139,34)")
        p:indexColor("LIME","rgb(20,255,20)")
        p:indexColor("LIME_GREEN","rgb(50,205,50)")
        p:indexColor("LIGHT_GREEN","rgb(144,238,144)")
        p:indexColor("PALE_GREEN","rgb(152,251,152)")
        p:indexColor("DARK_SEA_GREEN","rgb(143,188,143)")
        p:indexColor("MEDIUM_SPRING_GREEN","rgb(20,250,154)")
        p:indexColor("SPRING_GREEN","rgb(20,255,127)")
        p:indexColor("SEA_GREEN","rgb(46,139,87)")
        p:indexColor("MEDIUM_AQUA_MARINE","rgb(102,205,170)")
        p:indexColor("MEDIUM_SEA_GREEN","rgb(60,179,113)")
        p:indexColor("LIGHT_SEA_GREEN","rgb(32,178,170)")
        p:indexColor("DARK_SLATE_GRAY","rgb(47,79,79)")
        p:indexColor("TEAL","rgb(20,128,128)")
        p:indexColor("DARK_CYAN","rgb(20,139,139)")
        p:indexColor("LIGHT_CYAN","rgb(224,255,255)")
        p:indexColor("DARK_TURQUOISE","rgb(20,206,209)")
        p:indexColor("TURQUOISE","rgb(64,224,208)")
        p:indexColor("MEDIUM_TURQUOISE","rgb(72,209,204)")
        p:indexColor("PALE_TURQUOISE","rgb(175,238,238)")
        p:indexColor("AQUA_MARINE","rgb(127,255,212)")
        p:indexColor("POWDER_BLUE","rgb(176,224,230)")
        p:indexColor("CADET_BLUE","rgb(95,158,160)")
        p:indexColor("STEEL_BLUE","rgb(70,130,180)")
        p:indexColor("CORN_FLOWER_BLUE","rgb(100,149,237)")
        p:indexColor("DEEP_SKY_BLUE","rgb(20,191,255)")
        p:indexColor("DODGER_BLUE","rgb(30,144,255)")
        p:indexColor("LIGHT_BLUE","rgb(173,216,230)")
        p:indexColor("SKY_BLUE","rgb(135,206,235)")
        p:indexColor("LIGHT_SKY_BLUE","rgb(135,206,250)")
        p:indexColor("MIDNIGHT_BLUE","rgb(25,25,112)")
        p:indexColor("NAVY","rgb(20,20,128)")
        p:indexColor("DARK_BLUE","rgb(20,20,139)")
        p:indexColor("MEDIUM_BLUE","rgb(20,20,205)")
        p:indexColor("BLUE","rgb(20,20,255)")
        p:indexColor("ROYAL_BLUE","rgb(65,105,225)")
        p:indexColor("BLUE_VIOLET","rgb(138,43,226)")
        p:indexColor("INDIGO","rgb(75,20,130)")
        p:indexColor("DARK_SLATE_BLUE","rgb(72,61,139)")
        p:indexColor("SLATE_BLUE","rgb(106,90,205)")
        p:indexColor("MEDIUM_SLATE_BLUE","rgb(123,104,238)")
        p:indexColor("MEDIUM_PURPLE","rgb(147,112,219)")
        p:indexColor("DARK_MAGENTA","rgb(139,20,139)")
        p:indexColor("DARK_VIOLET","rgb(148,20,211)")
        p:indexColor("DARK_ORCHID","rgb(153,50,204)")
        p:indexColor("MEDIUM_ORCHID","rgb(186,85,211)")
        p:indexColor("PURPLE","rgb(128,20,128)")
        p:indexColor("THISTLE","rgb(216,191,216)")
        p:indexColor("PLUM","rgb(221,160,221)")
        p:indexColor("VIOLET","rgb(238,130,238)")
        p:indexColor("MAGENTA","rgb(255,20,255)")
        p:indexColor("ORCHID","rgb(218,112,214)")
        p:indexColor("MEDIUM_VIOLET_RED","rgb(199,21,133)")
        p:indexColor("PALE_VIOLET_RED","rgb(219,112,147)")
        p:indexColor("DEEP_PINK","rgb(255,20,147)")
        p:indexColor("HOT_PINK","rgb(255,105,180)")
        p:indexColor("LIGHT_PINK","rgb(255,182,193)")
        p:indexColor("PINK","rgb(255,192,203)")
        p:indexColor("ANTIQUE_WHITE","rgb(250,235,215)")
        p:indexColor("BEIGE","rgb(245,245,220)")
        p:indexColor("BISQUE","rgb(255,228,196)")
        p:indexColor("BLANCHED_ALMOND","rgb(255,235,205)")
        p:indexColor("WHEAT","rgb(245,222,179)")
        p:indexColor("CORN_SILK","rgb(255,248,220)")
        p:indexColor("LEMON_CHIFFON","rgb(255,250,205)")
        p:indexColor("LIGHT_GOLDEN_ROD_YELLOW","rgb(250,250,210)")
        p:indexColor("LIGHT_YELLOW","rgb(255,255,224)")
        p:indexColor("SADDLE_BROWN","rgb(139,69,19)")
        p:indexColor("CALM_PURPLE","rgb(85,85,127)")
        p:indexColor("SIENNA","rgb(160,82,45)")
        p:indexColor("CHOCOLATE","rgb(210,105,30)")
        p:indexColor("PERU","rgb(205,133,63)")
        p:indexColor("SANDY_BROWN","rgb(244,164,96)")
        p:indexColor("BURLY_WOOD","rgb(222,184,135)")
        p:indexColor("TAN","rgb(210,180,140)")
        p:indexColor("ROSY_BROWN","rgb(188,143,143)")
        p:indexColor("MOCCASIN","rgb(255,228,181)")
        p:indexColor("NAVAJO_WHITE","rgb(255,222,173)")
        p:indexColor("PEACH_PUFF","rgb(255,218,185)")
        p:indexColor("MISTY_ROSE","rgb(255,228,225)")
        p:indexColor("LAVENDER_BLUSH","rgb(255,240,245)")
        p:indexColor("LINEN","rgb(250,240,230)")
        p:indexColor("OLD_LACE","rgb(253,245,230)")
        p:indexColor("PAPAYA_WHIP","rgb(255,239,213)")
        p:indexColor("SEA_SHELL","rgb(255,245,238)")
        p:indexColor("MINT_CREAM","rgb(245,255,250)")
        p:indexColor("SLATE_GRAY","rgb(112,128,144)")
        p:indexColor("LIGHT_SLATE_GRAY","rgb(119,136,153)")
        p:indexColor("LIGHT_STEEL_BLUE","rgb(176,196,222)")
        p:indexColor("LAVENDEr(","rgb(230,230,250)")
        p:indexColor("FLORAL_WHITE","rgb(255,250,240)")
        p:indexColor("ALICE_BLUE","rgb(240,248,255)")
        p:indexColor("GHOST_WHITE","rgb(248,248,255)")
        p:indexColor("HONEYDEW","rgb(240,255,240)")
        p:indexColor("IVORY","rgb(255,255,240)")
        p:indexColor("AZURE","rgb(240,255,255)")
        p:indexColor("SNOW","rgb(255,250,250)")
        p:indexColor("DIM_GRAY","rgb(105,105,105)")
        p:indexColor("GRAY","rgb(128,128,128)")
        p:indexColor("DARK_GRAY","rgb(169,169,169)")
        p:indexColor("SILVEr(","rgb(192,192,192)")
        p:indexColor("LIGHT_GRAY","rgb(211,211,211)")
        p:indexColor("GAINSBORO","rgb(220,220,220)")
        p:indexColor("WHITE_SMOKE","rgb(245,245,245)")
        p:indexColor("AliceBlue","#f0f8ff")
        p:indexColor("AntiqueWhite","#faebd7")
        p:indexColor("AntiqueWhite1","#ffefdb")
        p:indexColor("AntiqueWhite2","#eedfcc")
        p:indexColor("AntiqueWhite3","#cdc0b0")
        p:indexColor("AntiqueWhite4","#8b8378")
        p:indexColor("aquamarine1","#7fffd4")
        p:indexColor("aquamarine2","#76eec6")
        p:indexColor("aquamarine4","#458b74")
        p:indexColor("azure1","#f0ffff")
        p:indexColor("azure2","#e0eeee")
        p:indexColor("azure3","#c1cdcd")
        p:indexColor("azure4","#838b8b")
        p:indexColor("beige","#f5f5dc")
        p:indexColor("bisque1","#ffe4c4")
        p:indexColor("bisque2","#eed5b7")
        p:indexColor("bisque3","#cdb79e")
        p:indexColor("bisque4","#8b7d6b")
        p:indexColor("BlanchedAlmond","#ffebcd")
        p:indexColor("blue1","#0000ff")
        p:indexColor("blue2","#0000ee")
        p:indexColor("blue4","#00008b")
        p:indexColor("BlueViolet","#8a2be2")
        p:indexColor("brown","#a52a2a")
        p:indexColor("brown1","#ff4040")
        p:indexColor("brown2","#ee3b3b")
        p:indexColor("brown3","#cd3333")
        p:indexColor("brown4","#8b2323")
        p:indexColor("burlywood","#deb887")
        p:indexColor("burlywood1","#ffd39b")
        p:indexColor("burlywood2","#eec591")
        p:indexColor("burlywood3","#cdaa7d")
        p:indexColor("burlywood4","#8b7355")
        p:indexColor("CadetBlue","#5f9ea0")
        p:indexColor("CadetBlue1","#98f5ff")
        p:indexColor("CadetBlue2","#8ee5ee")
        p:indexColor("CadetBlue3","#7ac5cd")
        p:indexColor("CadetBlue4","#53868b")
        p:indexColor("chartreuse1","#7fff00")
        p:indexColor("chartreuse2","#76ee00")
        p:indexColor("chartreuse3","#66cd00")
        p:indexColor("chartreuse4","#458b00")
        p:indexColor("chocolate","#d2691e")
        p:indexColor("chocolate1","#ff7f24")
        p:indexColor("chocolate2","#ee7621")
        p:indexColor("chocolate3","#cd661d")
        p:indexColor("coral","#ff7f50")
        p:indexColor("coral1","#ff7256")
        p:indexColor("coral2","#ee6a50")
        p:indexColor("coral3","#cd5b45")
        p:indexColor("coral4","#8b3e2f")
        p:indexColor("CornflowerBlue","#6495ed")
        p:indexColor("cornsilk1","#fff8dc")
        p:indexColor("cornsilk2","#eee8cd")
        p:indexColor("cornsilk3","#cdc8b1")
        p:indexColor("cornsilk4","#8b8878")
        p:indexColor("cyan1","#00ffff")
        p:indexColor("cyan2","#00eeee")
        p:indexColor("cyan3","#00cdcd")
        p:indexColor("cyan4","#008b8b")
        p:indexColor("DarkGoldenrod","#b8860b")
        p:indexColor("DarkGoldenrod1","#ffb90f")
        p:indexColor("DarkGoldenrod2","#eead0e")
        p:indexColor("DarkGoldenrod3","#cd950c")
        p:indexColor("DarkGoldenrod4","#8b6508")
        p:indexColor("DarkGreen","#006400")
        p:indexColor("DarkKhaki","#bdb76b")
        p:indexColor("DarkOliveGreen","#556b2f")
        p:indexColor("DarkOliveGreen1","#caff70")
        p:indexColor("DarkOliveGreen2","#bcee68")
        p:indexColor("DarkOliveGreen3","#a2cd5a")
        p:indexColor("DarkOliveGreen4","#6e8b3d")
        p:indexColor("DarkOrange","#ff8c00")
        p:indexColor("DarkOrange1","#ff7f00")
        p:indexColor("DarkOrange2","#ee7600")
        p:indexColor("DarkOrange3","#cd6600")
        p:indexColor("DarkOrange4","#8b4500")
        p:indexColor("DarkOrchid","#9932cc")
        p:indexColor("DarkOrchid1","#bf3eff")
        p:indexColor("DarkOrchid2","#b23aee")
        p:indexColor("DarkOrchid3","#9a32cd")
        p:indexColor("DarkOrchid4","#68228b")
        p:indexColor("DarkSalmon","#e9967a")
        p:indexColor("DarkSeaGreen","#8fbc8f")
        p:indexColor("DarkSeaGreen1","#c1ffc1")
        p:indexColor("DarkSeaGreen2","#b4eeb4")
        p:indexColor("DarkSeaGreen3","#9bcd9b")
        p:indexColor("DarkSeaGreen4","#698b69")
        p:indexColor("DarkSlateBlue","#483d8b")
        p:indexColor("DarkSlateGray","#2f4f4f")
        p:indexColor("DarkSlateGray1","#97ffff")
        p:indexColor("DarkSlateGray2","#8deeee")
        p:indexColor("DarkSlateGray3","#79cdcd")
        p:indexColor("DarkSlateGray4","#528b8b")
        p:indexColor("DarkTurquoise","#00ced1")
        p:indexColor("DarkViolet","#9400d3")
        p:indexColor("DeepPink1","#ff1493")
        p:indexColor("DeepPink2","#ee1289")
        p:indexColor("DeepPink3","#cd1076")
        p:indexColor("DeepPink4","#8b0a50")
        p:indexColor("DeepSkyBlue1","#00bfff")
        p:indexColor("DeepSkyBlue2","#00b2ee")
        p:indexColor("DeepSkyBlue3","#009acd")
        p:indexColor("DeepSkyBlue4","#00688b")
        p:indexColor("DimGray","#696969")
        p:indexColor("DodgerBlue1","#1e90ff")
        p:indexColor("DodgerBlue2","#1c86ee")
        p:indexColor("DodgerBlue3","#1874cd")
        p:indexColor("DodgerBlue4","#104e8b")
        p:indexColor("firebrick","#b22222")
        p:indexColor("firebrick1","#ff3030")
        p:indexColor("firebrick2","#ee2c2c")
        p:indexColor("firebrick3","#cd2626")
        p:indexColor("firebrick4","#8b1a1a")
        p:indexColor("FloralWhite","#fffaf0")
        p:indexColor("ForestGreen","#228b22")
        p:indexColor("gainsboro","#dcdcdc")
        p:indexColor("GhostWhite","#f8f8ff")
        p:indexColor("gold1","#ffd700")
        p:indexColor("gold2","#eec900")
        p:indexColor("gold3","#cdad00")
        p:indexColor("gold4","#8b7500")
        p:indexColor("goldenrod","#daa520")
        p:indexColor("goldenrod1","#ffc125")
        p:indexColor("goldenrod2","#eeb422")
        p:indexColor("goldenrod3","#cd9b1d")
        p:indexColor("goldenrod4","#8b6914")
        p:indexColor("gray","#bebebe")
        p:indexColor("green1","#00ff00")
        p:indexColor("green2","#00ee00")
        p:indexColor("green3","#00cd00")
        p:indexColor("green4","#008b00")
        p:indexColor("GreenYellow","#adff2f")
        p:indexColor("honeydew1","#f0fff0")
        p:indexColor("honeydew2","#e0eee0")
        p:indexColor("honeydew3","#c1cdc1")
        p:indexColor("honeydew4","#838b83")
        p:indexColor("HotPink","#ff69b4")
        p:indexColor("HotPink1","#ff6eb4")
        p:indexColor("HotPink2","#ee6aa7")
        p:indexColor("HotPink3","#cd6090")
        p:indexColor("HotPink4","#8b3a62")
        p:indexColor("IndianRed","#cd5c5c")
        p:indexColor("IndianRed1","#ff6a6a")
        p:indexColor("IndianRed2","#ee6363")
        p:indexColor("IndianRed3","#cd5555")
        p:indexColor("IndianRed4","#8b3a3a")
        p:indexColor("ivory1","#fffff0")
        p:indexColor("ivory2","#eeeee0")
        p:indexColor("ivory3","#cdcdc1")
        p:indexColor("ivory4","#8b8b83")
        p:indexColor("khaki","#f0e68c")
        p:indexColor("khaki1","#fff68f")
        p:indexColor("khaki2","#eee685")
        p:indexColor("khaki3","#cdc673")
        p:indexColor("khaki4","#8b864e")
        p:indexColor("lavender","#e6e6fa")
        p:indexColor("LavenderBlush1","#fff0f5")
        p:indexColor("LavenderBlush2","#eee0e5")
        p:indexColor("LavenderBlush3","#cdc1c5")
        p:indexColor("LavenderBlush4","#8b8386")
        p:indexColor("LawnGreen","#7cfc00")
        p:indexColor("LemonChiffon1","#fffacd")
        p:indexColor("LemonChiffon2","#eee9bf")
        p:indexColor("LemonChiffon3","#cdc9a5")
        p:indexColor("LemonChiffon4","#8b8970")
        p:indexColor("light","#eedd82")
        p:indexColor("LightBlue","#add8e6")
        p:indexColor("LightBlue1","#bfefff")
        p:indexColor("LightBlue2","#b2dfee")
        p:indexColor("LightBlue3","#9ac0cd")
        p:indexColor("LightBlue4","#68838b")
        p:indexColor("LightCoral","#f08080")
        p:indexColor("LightCyan1","#e0ffff")
        p:indexColor("LightCyan2","#d1eeee")
        p:indexColor("LightCyan3","#b4cdcd")
        p:indexColor("LightCyan4","#7a8b8b")
        p:indexColor("LightGoldenrod1","#ffec8b")
        p:indexColor("LightGoldenrod2","#eedc82")
        p:indexColor("LightGoldenrod3","#cdbe70")
        p:indexColor("LightGoldenrod4","#8b814c")
        p:indexColor("LightGoldenrodYellow","#fafad2")
        p:indexColor("LightGray","#d3d3d3")
        p:indexColor("LightPink","#ffb6c1")
        p:indexColor("LightPink1","#ffaeb9")
        p:indexColor("LightPink2","#eea2ad")
        p:indexColor("LightPink3","#cd8c95")
        p:indexColor("LightPink4","#8b5f65")
        p:indexColor("LightSalmon1","#ffa07a")
        p:indexColor("LightSalmon2","#ee9572")
        p:indexColor("LightSalmon3","#cd8162")
        p:indexColor("LightSalmon4","#8b5742")
        p:indexColor("LightSeaGreen","#20b2aa")
        p:indexColor("LightSkyBlue","#87cefa")
        p:indexColor("LightSkyBlue1","#b0e2ff")
        p:indexColor("LightSkyBlue2","#a4d3ee")
        p:indexColor("LightSkyBlue3","#8db6cd")
        p:indexColor("LightSkyBlue4","#607b8b")
        p:indexColor("LightSlateBlue","#8470ff")
        p:indexColor("LightSlateGray","#778899")
        p:indexColor("LightSteelBlue","#b0c4de")
        p:indexColor("LightSteelBlue1","#cae1ff")
        p:indexColor("LightSteelBlue2","#bcd2ee")
        p:indexColor("LightSteelBlue3","#a2b5cd")
        p:indexColor("LightSteelBlue4","#6e7b8b")
        p:indexColor("LightYellow1","#ffffe0")
        p:indexColor("LightYellow2","#eeeed1")
        p:indexColor("LightYellow3","#cdcdb4")
        p:indexColor("LightYellow4","#8b8b7a")
        p:indexColor("LimeGreen","#32cd32")
        p:indexColor("linen","#faf0e6")
        p:indexColor("magenta","#ff00ff")
        p:indexColor("magenta2","#ee00ee")
        p:indexColor("magenta3","#cd00cd")
        p:indexColor("magenta4","#8b008b")
        p:indexColor("maroon","#b03060")
        p:indexColor("maroon1","#ff34b3")
        p:indexColor("maroon2","#ee30a7")
        p:indexColor("maroon3","#cd2990")
        p:indexColor("maroon4","#8b1c62")
        p:indexColor("medium","#66cdaa")
        p:indexColor("MediumAquamarine","#66cdaa")
        p:indexColor("MediumBlue","#0000cd")
        p:indexColor("MediumOrchid","#ba55d3")
        p:indexColor("MediumOrchid1","#e066ff")
        p:indexColor("MediumOrchid2","#d15fee")
        p:indexColor("MediumOrchid3","#b452cd")
        p:indexColor("MediumOrchid4","#7a378b")
        p:indexColor("MediumPurple","#9370db")
        p:indexColor("MediumPurple1","#ab82ff")
        p:indexColor("MediumPurple2","#9f79ee")
        p:indexColor("MediumPurple3","#8968cd")
        p:indexColor("MediumPurple4","#5d478b")
        p:indexColor("MediumSeaGreen","#3cb371")
        p:indexColor("MediumSlateBlue","#7b68ee")
        p:indexColor("MediumSpringGreen","#00fa9a")
        p:indexColor("MediumTurquoise","#48d1cc")
        p:indexColor("MediumVioletRed","#c71585")
        p:indexColor("MidnightBlue","#191970")
        p:indexColor("MintCream","#f5fffa")
        p:indexColor("MistyRose1","#ffe4e1")
        p:indexColor("MistyRose2","#eed5d2")
        p:indexColor("MistyRose3","#cdb7b5")
        p:indexColor("MistyRose4","#8b7d7b")
        p:indexColor("moccasin","#ffe4b5")
        p:indexColor("NavajoWhite1","#ffdead")
        p:indexColor("NavajoWhite2","#eecfa1")
        p:indexColor("NavajoWhite3","#cdb38b")
        p:indexColor("NavajoWhite4","#8b795e")
        p:indexColor("NavyBlue","#000080")
        p:indexColor("OldLace","#fdf5e6")
        p:indexColor("OliveDrab","#6b8e23")
        p:indexColor("OliveDrab1","#c0ff3e")
        p:indexColor("OliveDrab2","#b3ee3a")
        p:indexColor("OliveDrab4","#698b22")
        p:indexColor("orange1","#ffa500")
        p:indexColor("orange2","#ee9a00")
        p:indexColor("orange3","#cd8500")
        p:indexColor("orange4","#8b5a00")
        p:indexColor("OrangeRed1","#ff4500")
        p:indexColor("OrangeRed2","#ee4000")
        p:indexColor("OrangeRed3","#cd3700")
        p:indexColor("OrangeRed4","#8b2500")
        p:indexColor("orchid","#da70d6")
        p:indexColor("orchid1","#ff83fa")
        p:indexColor("orchid2","#ee7ae9")
        p:indexColor("orchid3","#cd69c9")
        p:indexColor("orchid4","#8b4789")
        p:indexColor("pale","#db7093")
        p:indexColor("PaleGoldenrod","#eee8aa")
        p:indexColor("PaleGreen","#98fb98")
        p:indexColor("PaleGreen1","#9aff9a")
        p:indexColor("PaleGreen2","#90ee90")
        p:indexColor("PaleGreen3","#7ccd7c")
        p:indexColor("PaleGreen4","#548b54")
        p:indexColor("PaleTurquoise","#afeeee")
        p:indexColor("PaleTurquoise1","#bbffff")
        p:indexColor("PaleTurquoise2","#aeeeee")
        p:indexColor("PaleTurquoise3","#96cdcd")
        p:indexColor("PaleTurquoise4","#668b8b")
        p:indexColor("PaleVioletRed","#db7093")
        p:indexColor("PaleVioletRed1","#ff82ab")
        p:indexColor("PaleVioletRed2","#ee799f")
        p:indexColor("PaleVioletRed3","#cd6889")
        p:indexColor("PaleVioletRed4","#8b475d")
        p:indexColor("PapayaWhip","#ffefd5")
        p:indexColor("PeachPuff1","#ffdab9")
        p:indexColor("PeachPuff2","#eecbad")
        p:indexColor("PeachPuff3","#cdaf95")
        p:indexColor("PeachPuff4","#8b7765")
        p:indexColor("pink","#ffc0cb")
        p:indexColor("pink1","#ffb5c5")
        p:indexColor("pink2","#eea9b8")
        p:indexColor("pink3","#cd919e")
        p:indexColor("pink4","#8b636c")
        p:indexColor("plum","#dda0dd")
        p:indexColor("plum1","#ffbbff")
        p:indexColor("plum2","#eeaeee")
        p:indexColor("plum3","#cd96cd")
        p:indexColor("plum4","#8b668b")
        p:indexColor("PowderBlue","#b0e0e6")
        p:indexColor("purple","#a020f0")
        p:indexColor("purple1","#9b30ff")
        p:indexColor("purple2","#912cee")
        p:indexColor("purple3","#7d26cd")
        p:indexColor("purple4","#551a8b")
        p:indexColor("red1","#ff0000")
        p:indexColor("red2","#ee0000")
        p:indexColor("red3","#cd0000")
        p:indexColor("red4","#8b0000")
        p:indexColor("RosyBrown","#bc8f8f")
        p:indexColor("RosyBrown1","#ffc1c1")
        p:indexColor("RosyBrown2","#eeb4b4")
        p:indexColor("RosyBrown3","#cd9b9b")
        p:indexColor("RosyBrown4","#8b6969")
        p:indexColor("RoyalBlue","#4169e1")
        p:indexColor("RoyalBlue1","#4876ff")
        p:indexColor("RoyalBlue2","#436eee")
        p:indexColor("RoyalBlue3","#3a5fcd")
        p:indexColor("RoyalBlue4","#27408b")
        p:indexColor("SaddleBrown","#8b4513")
        p:indexColor("salmon","#fa8072")
        p:indexColor("salmon1","#ff8c69")
        p:indexColor("salmon2","#ee8262")
        p:indexColor("salmon3","#cd7054")
        p:indexColor("salmon4","#8b4c39")
        p:indexColor("SandyBrown","#f4a460")
        p:indexColor("SeaGreen1","#54ff9f")
        p:indexColor("SeaGreen2","#4eee94")
        p:indexColor("SeaGreen3","#43cd80")
        p:indexColor("SeaGreen4","#2e8b57")
        p:indexColor("seashell1","#fff5ee")
        p:indexColor("seashell2","#eee5de")
        p:indexColor("seashell3","#cdc5bf")
        p:indexColor("seashell4","#8b8682")
        p:indexColor("sienna","#a0522d")
        p:indexColor("sienna1","#ff8247")
        p:indexColor("sienna2","#ee7942")
        p:indexColor("sienna3","#cd6839")
        p:indexColor("sienna4","#8b4726")
        p:indexColor("SkyBlue","#87ceeb")
        p:indexColor("SkyBlue1","#87ceff")
        p:indexColor("SkyBlue2","#7ec0ee")
        p:indexColor("SkyBlue3","#6ca6cd")
        p:indexColor("SkyBlue4","#4a708b")
        p:indexColor("SlateBlue","#6a5acd")
        p:indexColor("SlateBlue1","#836fff")
        p:indexColor("SlateBlue2","#7a67ee")
        p:indexColor("SlateBlue3","#6959cd")
        p:indexColor("SlateBlue4","#473c8b")
        p:indexColor("SlateGray","#708090")
        p:indexColor("SlateGray1","#c6e2ff")
        p:indexColor("SlateGray2","#b9d3ee")
        p:indexColor("SlateGray3","#9fb6cd")
        p:indexColor("SlateGray4","#6c7b8b")
        p:indexColor("snow1","#fffafa")
        p:indexColor("snow2","#eee9e9")
        p:indexColor("snow3","#cdc9c9")
        p:indexColor("snow4","#8b8989")
        p:indexColor("SpringGreen1","#00ff7f")
        p:indexColor("SpringGreen2","#00ee76")
        p:indexColor("SpringGreen3","#00cd66")
        p:indexColor("SpringGreen4","#008b45")
        p:indexColor("SteelBlue","#4682b4")
        p:indexColor("SteelBlue1","#63b8ff")
        p:indexColor("SteelBlue2","#5cacee")
        p:indexColor("SteelBlue3","#4f94cd")
        p:indexColor("SteelBlue4","#36648b")
        p:indexColor("tan","#d2b48c")
        p:indexColor("tan1","#ffa54f")
        p:indexColor("tan2","#ee9a49")
        p:indexColor("tan3","#cd853f")
        p:indexColor("tan4","#8b5a2b")
        p:indexColor("thistle","#d8bfd8")
        p:indexColor("thistle1","#ffe1ff")
        p:indexColor("thistle2","#eed2ee")
        p:indexColor("thistle3","#cdb5cd")
        p:indexColor("thistle4","#8b7b8b")
        p:indexColor("tomato1","#ff6347")
        p:indexColor("tomato2","#ee5c42")
        p:indexColor("tomato3","#cd4f39")
        p:indexColor("tomato4","#8b3626")
        p:indexColor("turquoise","#40e0d0")
        p:indexColor("turquoise1","#00f5ff")
        p:indexColor("turquoise2","#00e5ee")
        p:indexColor("turquoise3","#00c5cd")
        p:indexColor("turquoise4","#00868b")
        p:indexColor("violet","#ee82ee")
        p:indexColor("VioletRed","#d02090")
        p:indexColor("VioletRed1","#ff3e96")
        p:indexColor("VioletRed2","#ee3a8c")
        p:indexColor("VioletRed3","#cd3278")
        p:indexColor("VioletRed4","#8b2252")
        p:indexColor("wheat","#f5deb3")
        p:indexColor("wheat1","#ffe7ba")
        p:indexColor("wheat2","#eed8ae")
        p:indexColor("wheat3","#cdba96")
        p:indexColor("wheat4","#8b7e66")
        p:indexColor("WhiteSmoke","#f5f5f5")
        p:indexColor("yellow1","#ffff00")
        p:indexColor("yellow2","#eeee00")
        p:indexColor("yellow3","#cdcd00")
        p:indexColor("yellow4","#8b8b00")
        p:indexColor("YellowGreen","#9acd32")
        p:indexColor("purple","#7e1e9c")
        p:indexColor("green","#12a217")
        p:indexColor("blue","#0343df")
        p:indexColor("pink","#ff81c0")
        p:indexColor("brown","#653700")
        p:indexColor("red","#e50000")
        p:indexColor("light_blue","#95d0fc")
        p:indexColor("teal","#029386")
        p:indexColor("orange","#f97306")
        p:indexColor("light_green","#96f97b")
        p:indexColor("magenta","#c20078")
        p:indexColor("yellow","#ffff14")
        p:indexColor("sky_blue","#75bbfd")
        p:indexColor("grey","#929591")
        p:indexColor("lime_green","#89fe05")
        p:indexColor("light_purple","#bf77f6")
        p:indexColor("violet","#9a0eea")
        p:indexColor("dark_green","#033500")
        p:indexColor("turquoise","#06c2ac")
        p:indexColor("lavender","#c79fef")
        p:indexColor("dark_blue","#00035b")
        p:indexColor("tan","#d1b26f")
        p:indexColor("cyan","#00ffff")
        p:indexColor("aqua","#13eac9")
        p:indexColor("forest_green","#06470c")
        p:indexColor("mauve","#ae7181")
        p:indexColor("dark_purple","#35063e")
        p:indexColor("bright_green","#01ff07")
        p:indexColor("maroon","#650021")
        p:indexColor("olive","#6e750e")
        p:indexColor("salmon","#ff796c")
        p:indexColor("beige","#e6daa6")
        p:indexColor("royal_blue","#0504aa")
        p:indexColor("navy_blue","#001146")
        p:indexColor("lilac","#cea2fd")
        p:indexColor("black","#000000")
        p:indexColor("hot_pink","#ff028d")
        p:indexColor("light_brown","#ad8150")
        p:indexColor("pale_green","#c7fdb5")
        p:indexColor("peach","#ffb07c")
        p:indexColor("olive_green","#677a04")
        p:indexColor("dark_pink","#cb416b")
        p:indexColor("periwinkle","#8e82fe")
        p:indexColor("sea_green","#53fca1")
        p:indexColor("lime","#aaff32")
        p:indexColor("indigo","#380282")
        p:indexColor("mustard","#ceb301")
        p:indexColor("light_pink","#ffd1df")
        p:indexColor("rose","#cf6275")
        p:indexColor("bright_blue","#0165fc")
        p:indexColor("neon_green","#0cff0c")
        p:indexColor("burnt_orange","#c04e01")
        p:indexColor("aquamarine","#04d8b2")
        p:indexColor("navy","#01153e")
        p:indexColor("grass_green","#3f9b0b")
        p:indexColor("pale_blue","#d0fefe")
        p:indexColor("dark_red","#840000")
        p:indexColor("bright_purple","#be03fd")
        p:indexColor("yellow_green","#c0fb2d")
        p:indexColor("baby_blue","#a2cffe")
        p:indexColor("gold","#dbb40c")
        p:indexColor("mint_green","#8fff9f")
        p:indexColor("plum","#580f41")
        p:indexColor("royal_purple","#4b006e")
        p:indexColor("brick_red","#8f1402")
        p:indexColor("dark_teal","#014d4e")
        p:indexColor("burgundy","#610023")
        p:indexColor("khaki","#aaa662")
        p:indexColor("blue_green","#137e6d")
        p:indexColor("seafoam_green","#7af9ab")
        p:indexColor("kelly_green","#02ab2e")
        p:indexColor("puke_green","#9aae07")
        p:indexColor("pea_green","#8eab12")
        p:indexColor("taupe","#b9a281")
        p:indexColor("dark_brown","#341c02")
        p:indexColor("deep_purple","#36013f")
        p:indexColor("chartreuse","#c1f80a")
        p:indexColor("bright_pink","#fe01b1")
        p:indexColor("light_orange","#fdaa48")
        p:indexColor("mint","#9ffeb0")
        p:indexColor("pastel_green","#b0ff9d")
        p:indexColor("sand","#e2ca76")
        p:indexColor("dark_orange","#c65102")
        p:indexColor("spring_green","#a9f971")
        p:indexColor("puce","#a57e52")
        p:indexColor("seafoam","#80f9ad")
        p:indexColor("grey_blue","#6b8ba4")
        p:indexColor("army_green","#4b5d16")
        p:indexColor("dark_grey","#363737")
        p:indexColor("dark_yellow","#d5b60a")
        p:indexColor("goldenrod","#fac205")
        p:indexColor("slate","#516572")
        p:indexColor("light_teal","#90e4c1")
        p:indexColor("rust","#a83c09")
        p:indexColor("deep_blue","#040273")
        p:indexColor("pale_pink","#ffcfdc")
        p:indexColor("cerulean","#0485d1")
        p:indexColor("light_red","#ff474c")
        p:indexColor("mustard_yellow","#d2bd0a")
        p:indexColor("ochre","#bf9005")
        p:indexColor("pale_yellow","#ffff84")
        p:indexColor("crimson","#8c000f")
        p:indexColor("fuchsia","#ed0dd9")
        p:indexColor("hunter_green","#0b4008")
        p:indexColor("blue_grey","#607c8e")
        p:indexColor("slate_blue","#5b7c99")
        p:indexColor("pale_purple","#b790d4")
        p:indexColor("sea_blue","#047495")
        p:indexColor("pinkish_purple","#d648d7")
        p:indexColor("puke","#a5a502")
        p:indexColor("light_grey","#d8dcd6")
        p:indexColor("leaf_green","#5ca904")
        p:indexColor("light_yellow","#fffe7a")
        p:indexColor("eggplant","#380835")
        p:indexColor("steel_blue","#5a7d9a")
        p:indexColor("moss_green","#658b38")
        p:indexColor("robin's_egg_blue","#98eff9")
        p:indexColor("white","#ffffff")
        p:indexColor("grey_green","#789b73")
        p:indexColor("sage","#87ae73")
        p:indexColor("brick","#a03623")
        p:indexColor("burnt_sienna","#b04e0f")
        p:indexColor("reddish_brown","#7f2b0a")
        p:indexColor("cream","#ffffc2")
        p:indexColor("coral","#fc5a50")
        p:indexColor("ocean_blue","#03719c")
        p:indexColor("greenish","#40a368")
        p:indexColor("dark_magenta","#960056")
        p:indexColor("red_orange","#fd3c06")
        p:indexColor("bluish_purple","#703be7")
        p:indexColor("midnight_blue","#020035")
        p:indexColor("light_violet","#d6b4fc")
        p:indexColor("dusty_rose","#c0737a")
        p:indexColor("medium_blue","#2c6fbb")
        p:indexColor("greenish_yellow","#cdfd02")
        p:indexColor("yellowish_green","#b0dd16")
        p:indexColor("purplish_blue","#601ef9")
        p:indexColor("greyish_blue","#5e819d")
        p:indexColor("grape","#6c3461")
        p:indexColor("light_olive","#acbf69")
        p:indexColor("cornflower_blue","#5170d7")
        p:indexColor("pinkish_red","#f10c45")
        p:indexColor("bright_red","#ff000d")
        p:indexColor("azure","#069af3")
        p:indexColor("blue_purple","#5729ce")
        p:indexColor("dark_turquoise","#045c5a")
        p:indexColor("electric_blue","#0652ff")
        p:indexColor("off_white","#ffffe4")
        p:indexColor("powder_blue","#b1d1fc")
        p:indexColor("wine","#80013f")
        p:indexColor("dull_green","#74a662")
        p:indexColor("apple_green","#76cd26")
        p:indexColor("light_turquoise","#7ef4cc")
        p:indexColor("neon_purple","#bc13fe")
        p:indexColor("cobalt","#1e488f")
        p:indexColor("pinkish","#d46a7e")
        p:indexColor("olive_drab","#6f7632")
        p:indexColor("dark_cyan","#0a888a")
        p:indexColor("purple_blue","#632de9")
        p:indexColor("dark_violet","#34013f")
        p:indexColor("dark_lavender","#856798")
        p:indexColor("forrest_green","#154406")
        p:indexColor("vomit","#a2a415")
        p:indexColor("pale_orange","#ffa756")
        p:indexColor("greenish_blue","#0b8b87")
        p:indexColor("dark_tan","#af884a")
        p:indexColor("green_blue","#06b48b")
        p:indexColor("bluish_green","#10a674")
        p:indexColor("pastel_blue","#a2bffe")
        p:indexColor("moss","#769958")
        p:indexColor("grass","#5cac2d")
        p:indexColor("deep_pink","#cb0162")
        p:indexColor("blood_red","#980002")
        p:indexColor("sage_green","#88b378")
        p:indexColor("aqua_blue","#02d8e9")
        p:indexColor("terracotta","#ca6641")
        p:indexColor("pastel_purple","#caa0ff")
        p:indexColor("sienna","#a9561e")
        p:indexColor("dark_olive","#373e02")
        p:indexColor("green_yellow","#c9ff27")
        p:indexColor("scarlet","#be0119")
        p:indexColor("greyish_green","#82a67d")
        p:indexColor("chocolate","#3d1c02")
        p:indexColor("blue_violet","#5d06e9")
        p:indexColor("cornflower","#6a79f7")
        p:indexColor("baby_pink","#ffb7ce")
        p:indexColor("charcoal","#343837")
        p:indexColor("pine_green","#0a481e")
        p:indexColor("pumpkin","#e17701")
        p:indexColor("greenish_brown","#696112")
        p:indexColor("red_brown","#8b2e16")
        p:indexColor("brownish_green","#6a6e09")
        p:indexColor("tangerine","#ff9408")
        p:indexColor("salmon_pink","#fe7b7c")
        p:indexColor("aqua_green","#12e193")
        p:indexColor("raspberry","#b00149")
        p:indexColor("greyish_purple","#887191")
        p:indexColor("rose_pink","#f7879a")
        p:indexColor("neon_pink","#fe019a")
        p:indexColor("cobalt_blue","#030aa7")
        p:indexColor("orange_brown","#be6400")
        p:indexColor("deep_red","#9a0200")
        p:indexColor("orange_red","#fd411e")
        p:indexColor("dirty_yellow","#cdc50a")
        p:indexColor("orchid","#c875c4")
        p:indexColor("reddish_pink","#fe2c54")
        p:indexColor("reddish_purple","#910951")
        p:indexColor("yellow_orange","#fcb001")
        p:indexColor("light_cyan","#acfffc")
        p:indexColor("sky","#82cafc")
        p:indexColor("light_magenta","#fa5ff7")
        p:indexColor("pale_red","#d9544d")
        p:indexColor("emerald","#01a049")
        p:indexColor("dark_beige","#ac9362")
        p:indexColor("ugly_green","#7a9703")
        p:indexColor("jade","#1fa774")
        p:indexColor("greenish_grey","#96ae8d")
        p:indexColor("dark_salmon","#c85a53")
        p:indexColor("purplish_pink","#ce5dae")
        p:indexColor("dark_aqua","#05696b")
        p:indexColor("brownish_orange","#cb7723")
        p:indexColor("light_olive_green","#a4be5c")
        p:indexColor("light_aqua","#8cffdb")
        p:indexColor("clay","#b66a50")
        p:indexColor("medium_green","#39ad48")
        p:indexColor("burnt_umber","#a0450e")
        p:indexColor("dull_blue","#49759c")
        p:indexColor("pale_brown","#b1916e")
        p:indexColor("emerald_green","#028f1e")
        p:indexColor("brownish","#9c6d57")
        p:indexColor("mud","#735c12")
        p:indexColor("dark_rose","#b5485d")
        p:indexColor("brownish_red","#9e3623")
        p:indexColor("pink_purple","#db4bda")
        p:indexColor("pinky_purple","#c94cbe")
        p:indexColor("camo_green","#526525")
        p:indexColor("faded_green","#7bb274")
        p:indexColor("dusty_pink","#d58a94")
        p:indexColor("purple_pink","#e03fd8")
        p:indexColor("vomit_green","#89a203")
        p:indexColor("deep_green","#02590f")
        p:indexColor("reddish_orange","#f8481c")
        p:indexColor("mahogany","#4a0100")
        p:indexColor("aubergine","#3d0734")
        p:indexColor("dull_pink","#d5869d")
        p:indexColor("evergreen","#05472a")
        p:indexColor("dark_sky_blue","#448ee4")
        p:indexColor("very_light_green","#d1ffbd")
        p:indexColor("pastel_pink","#ffbacd")
        p:indexColor("grey_purple","#826d8c")
        p:indexColor("very_light_blue","#d5ffff")
        p:indexColor("dark_mauve","#874c62")
        p:indexColor("cadet_blue","#4e7496")
        p:indexColor("ice_blue","#d7fffe")
        p:indexColor("light_tan","#fbeeac")
        p:indexColor("dirty_green","#667e2c")
        p:indexColor("neon_blue","#04d9ff")
        p:indexColor("wine_red","#7b0323")
        p:indexColor("chocolate_brown","#411900")
        p:indexColor("dull_purple","#84597e")
        p:indexColor("yellow_brown","#b79400")
        p:indexColor("denim","#3b638c")
        p:indexColor("eggshell","#ffffd4")
        p:indexColor("jungle_green","#048243")
        p:indexColor("dark_peach","#de7e5d")
        p:indexColor("poop","#7f5e00")
        p:indexColor("umber","#b26400")
        p:indexColor("light_lavender","#dfc5fe")
        p:indexColor("bright_yellow","#fffd01")
        p:indexColor("golden_yellow","#fec615")
        p:indexColor("dusty_blue","#5a86ad")
        p:indexColor("electric_green","#21fc0d")
        p:indexColor("lighter_green","#75fd63")
        p:indexColor("slate_grey","#59656d")
        p:indexColor("teal_green","#25a36f")
        p:indexColor("marine_blue","#01386a")
        p:indexColor("avocado","#90b134")
        p:indexColor("terra_cotta","#c9643b")
        p:indexColor("dusty_purple","#825f87")
        p:indexColor("light_maroon","#a24857")
        p:indexColor("reddish","#c44240")
        p:indexColor("dark_lilac","#9c6da5")
        p:indexColor("dark_periwinkle","#665fd1")
        p:indexColor("bluish_grey","#748b97")
        p:indexColor("puke_yellow","#c2be0e")
        p:indexColor("purplish","#94568c")
        p:indexColor("ultramarine","#2000b1")
        p:indexColor("barney_purple","#a00498")
        p:indexColor("forest","#0b5509")
        p:indexColor("pea_soup","#929901")
        p:indexColor("brownish_yellow","#c9b003")
        p:indexColor("bright_teal","#01f9c6")
        p:indexColor("bluegreen","#017a79")
        p:indexColor("green_brown","#544e03")
        p:indexColor("blurple","#5539cc")
        p:indexColor("light_sky_blue","#c6fcff")
        p:indexColor("periwinkle_blue","#8f99fb")
        p:indexColor("pale_violet","#ceaefa")
        p:indexColor("darker_green","#087804")
        p:indexColor("true_blue","#010fcc")
        p:indexColor("green_grey","#77926f")
        p:indexColor("grey_brown","#7f7053")
        p:indexColor("dark_olive_green","#3c4d03")
        p:indexColor("apricot","#ffb16d")
        p:indexColor("faded_purple","#916e99")
        p:indexColor("darker_blue","#011288")
        p:indexColor("cerise","#de0c62")
        p:indexColor("khaki_green","#728639")
        p:indexColor("burnt_red","#9f2305")
        p:indexColor("light_forest_green","#4f9153")
        p:indexColor("violet_blue","#510ac9")
        p:indexColor("pale_lavender","#eecffe")
        p:indexColor("acid_green","#8ffe09")
        p:indexColor("purple_grey","#866f85")
        p:indexColor("lemon","#fdff52")
        p:indexColor("bright_orange","#ff5b00")
        p:indexColor("soft_green","#6fc276")
        p:indexColor("blush","#f29e8e")
        p:indexColor("yellowish_brown","#9b7a01")
        p:indexColor("fluorescent_green","#08ff08")
        p:indexColor("electric_purple","#aa23ff")
        p:indexColor("steel","#738595")
        p:indexColor("dull_orange","#d8863b")
        p:indexColor("muddy_green","#657432")
        p:indexColor("marigold","#fcc006")
        p:indexColor("ocean","#017b92")
        p:indexColor("light_mauve","#c292a1")
        p:indexColor("bordeaux","#7b002c")
        p:indexColor("light_blue_green","#7efbb3")
        p:indexColor("yellowish","#faee66")
        p:indexColor("snot_green","#9dc100")
        p:indexColor("light_lime_green","#b9ff66")
        p:indexColor("drab_green","#749551")
        p:indexColor("faded_blue","#658cbb")
        p:indexColor("dark_forest_green","#002d04")
        p:indexColor("hot_purple","#cb00f5")
        p:indexColor("dark_maroon","#3c0008")
        p:indexColor("brown_green","#706c11")
        p:indexColor("swamp_green","#748500")
        p:indexColor("light_indigo","#6d5acf")
        p:indexColor("purpley_blue","#5f34e7")
        p:indexColor("lightish_blue","#3d7afd")
        p:indexColor("teal_blue","#01889f")
        p:indexColor("denim_blue","#3b5b92")
        p:indexColor("dark_lime_green","#7ebd01")
        p:indexColor("dull_yellow","#eedc5b")
        p:indexColor("pistachio","#c0fa8b")
        p:indexColor("lemon_yellow","#fdff38")
        p:indexColor("red_violet","#9e0168")
        p:indexColor("dusky_pink","#cc7a8b")
        p:indexColor("dirt","#8a6e45")
        p:indexColor("very_dark_green","#062e03")
        p:indexColor("medium_purple","#9e43a2")
        p:indexColor("shit","#7f5f00")
        p:indexColor("dark_mustard","#a88905")
        p:indexColor("pea_soup_green","#94a617")
        p:indexColor("bubblegum_pink","#fe83cc")
        p:indexColor("barbie_pink","#fe46a5")
        p:indexColor("military_green","#667c3e")
        p:indexColor("pale_teal","#82cbb2")
        p:indexColor("bronze","#a87900")
        p:indexColor("pinky_red","#fc2647")
        p:indexColor("dull_red","#bb3f3f")
        p:indexColor("darkish_blue","#014182")
        p:indexColor("bluish","#2976bb")
        p:indexColor("dark_gold","#b59410")
        p:indexColor("yellowy_green","#bff128")
        p:indexColor("pine","#2b5d34")
        p:indexColor("dark_blue_green","#005249")
        p:indexColor("dirty_pink","#ca7b80")
        p:indexColor("slate_green","#658d6d")
        p:indexColor("prussian_blue","#004577")
        p:indexColor("bright_violet","#ad0afd")
        p:indexColor("lighter_purple","#a55af4")
        p:indexColor("steel_grey","#6f828a")
        p:indexColor("russet","#a13905")
        p:indexColor("vermillion","#f4320c")
        p:indexColor("greyish_brown","#7a6a4f")
        p:indexColor("red_purple","#820747")
        p:indexColor("red_pink","#fa2a55")
        p:indexColor("bright_turquoise","#0ffef9")
        p:indexColor("golden_brown","#b27a01")
        p:indexColor("cerulean_blue","#056eee")
        p:indexColor("soft_blue","#6488ea")
        p:indexColor("easter_green","#8cfd7e")
        p:indexColor("amber","#feb308")
        p:indexColor("mid_blue","#276ab3")
        p:indexColor("shit_brown","#7b5804")
        p:indexColor("hospital_green","#9be5aa")
        p:indexColor("purpleish_blue","#6140ef")
        p:indexColor("purply_blue","#661aee")
        p:indexColor("silver","#c5c9c7")
        p:indexColor("sickly_green","#94b21c")
        p:indexColor("melon","#ff7855")
        p:indexColor("dusky_rose","#ba6873")
        p:indexColor("brown_orange","#b96902")
        p:indexColor("darkish_green","#287c37")
        p:indexColor("cranberry","#9e003a")
        p:indexColor("purpleish","#98568d")
        p:indexColor("ecru","#feffca")
        p:indexColor("darker_purple","#5f1b6b")
        p:indexColor("mocha","#9d7651")
        p:indexColor("bright_magenta","#ff08e8")
        p:indexColor("coffee","#a6814c")
        p:indexColor("sepia","#985e2b")
        p:indexColor("faded_red","#d3494e")
        p:indexColor("canary_yellow","#fffe40")
        p:indexColor("bluey_purple","#6241c7")
        p:indexColor("pastel_yellow","#fffe71")
        p:indexColor("pale_turquoise","#a5fbd5")
        p:indexColor("greyish_pink","#c88d94")
        p:indexColor("marine","#042e60")
        p:indexColor("purplish_grey","#7a687f")
        p:indexColor("camel","#c69f59")
        p:indexColor("brownish_grey","#86775f")
        p:indexColor("burnt_yellow","#d5ab09")
        p:indexColor("cherry_red","#f7022a")
        p:indexColor("orangey_brown","#b16002")
        p:indexColor("soft_pink","#fdb0c0")
        p:indexColor("dark_sea_green","#11875d")
        p:indexColor("aqua_marine","#2ee8bb")
        p:indexColor("robin_egg_blue","#8af1fe")
        p:indexColor("light_sea_green","#98f6b0")
        p:indexColor("mud_brown","#60460f")
        p:indexColor("sandstone","#c9ae74")
        p:indexColor("british_racing_green","#05480d")
        p:indexColor("faded_pink","#de9dac")
        p:indexColor("maize","#f4d054")
        p:indexColor("ocre","#c69c04")
        p:indexColor("orange_yellow","#ffad01")
        p:indexColor("dark_khaki","#9b8f55")
        p:indexColor("light_lime","#aefd6c")
        p:indexColor("bright_light_blue","#26f7fd")
        p:indexColor("jade_green","#2baf6a")
        p:indexColor("barney","#ac1db8")
        p:indexColor("adobe","#bd6c48")
        p:indexColor("minty_green","#0bf77d")
        p:indexColor("light_navy_blue","#2e5a88")
        p:indexColor("dusty_green","#76a973")
        p:indexColor("very_dark_blue","#000133")
        p:indexColor("ocean_green","#3d9973")
        p:indexColor("mustard_green","#a8b504")
        p:indexColor("poop_brown","#7a5901")
        p:indexColor("olive_brown","#645403")
        p:indexColor("pink_red","#f5054f")
        p:indexColor("light_navy","#155084")
        p:indexColor("very_light_purple","#f6cefc")
        p:indexColor("ivory","#ffffcb")
        p:indexColor("bright_lavender","#c760ff")
        p:indexColor("bright_aqua","#0bf9ea")
        p:indexColor("robin's_egg","#6dedfd")
        p:indexColor("muted_green","#5fa052")
        p:indexColor("medium_brown","#7f5112")
        p:indexColor("copper","#b66325")
        p:indexColor("dark_lime","#84b701")
        p:indexColor("strawberry","#fb2943")
        p:indexColor("dirt_brown","#836539")
        p:indexColor("celery","#c1fd95")
        p:indexColor("bright_sky_blue","#02ccfe")
        p:indexColor("poo_brown","#885f01")
        p:indexColor("pinkish_brown","#b17261")
        p:indexColor("celadon","#befdb7")
        p:indexColor("bright_lime_green","#65fe08")
        p:indexColor("auburn","#9a3001")
        p:indexColor("shocking_pink","#fe02a2")
        p:indexColor("mulberry","#920a4e")
        p:indexColor("carolina_blue","#8ab8fe")
        p:indexColor("lightish_green","#61e160")
        p:indexColor("light_lilac","#edc8ff")
        p:indexColor("pale_olive","#b9cc81")
        p:indexColor("pumpkin_orange","#fb7d07")
        p:indexColor("yellow_ochre","#cb9d06")
        p:indexColor("fire_engine_red","#fe0002")
        p:indexColor("deep_sky_blue","#0d75f8")
        p:indexColor("watermelon","#fd4659")
        p:indexColor("bottle_green","#044a05")
        p:indexColor("very_dark_purple","#2a0134")
        p:indexColor("wheat","#fbdd7e")
        p:indexColor("murky_green","#6c7a0e")
        p:indexColor("brownish_purple","#76424e")
        p:indexColor("kermit_green","#5cb200")
        p:indexColor("primary_blue","#0804f9")
        p:indexColor("orangey_red","#fa4224")
        p:indexColor("pale_lilac","#e4cbff")
        p:indexColor("rust_red","#aa2704")
        p:indexColor("dirty_orange","#c87606")
        p:indexColor("pinkish_grey","#c8aca9")
        p:indexColor("light_plum","#9d5783")
        p:indexColor("greeny_blue","#42b395")
        p:indexColor("dark_navy","#000435")
        p:indexColor("pink/purple","#ef1de7")
        p:indexColor("irish_green","#019529")
        p:indexColor("baby_poop","#937c00")
        p:indexColor("slime_green","#99cc04")
        p:indexColor("purplish_red","#b0054b")
        p:indexColor("rouge","#ab1239")
        p:indexColor("light_rose","#ffc5cb")
        p:indexColor("drab","#828344")
        p:indexColor("dark_navy_blue","#00022e")
        p:indexColor("light_yellow_green","#ccfd7f")
        p:indexColor("easter_purple","#c071fe")
        p:indexColor("snot","#acbb0d")
        p:indexColor("light_salmon","#fea993")
        p:indexColor("purpley_pink","#c83cb9")
        p:indexColor("poo","#8f7303")
        p:indexColor("berry","#990f4b")
        p:indexColor("medium_grey","#7d7f7c")
        p:indexColor("brown_red","#922b05")
        p:indexColor("blood","#770001")
        p:indexColor("soft_purple","#a66fb5")
        p:indexColor("grey_pink","#c3909b")
        p:indexColor("bluey_green","#2bb179")
        p:indexColor("midnight","#03012d")
        p:indexColor("dark_indigo","#1f0954")
        p:indexColor("warm_grey","#978a84")
        p:indexColor("sandy_brown","#c4a661")
        p:indexColor("cherry","#cf0234")
        p:indexColor("blue/purple","#5a06ef")
        p:indexColor("gunmetal","#536267")
        p:indexColor("deep_violet","#490648")
        p:indexColor("tree_green","#2a7e19")
        p:indexColor("orangish_brown","#b25f03")
        p:indexColor("shamrock_green","#02c14d")
        p:indexColor("orangish_red","#f43605")
        p:indexColor("greeny_yellow","#c6f808")
        p:indexColor("ugly_yellow","#d0c101")
        p:indexColor("french_blue","#436bad")
        p:indexColor("dusky_purple","#895b7b")
        p:indexColor("butter_yellow","#fffd74")
        p:indexColor("light_beige","#fffeb6")
        p:indexColor("golden","#f5bf03")
        p:indexColor("dusky_blue","#475f94")
        p:indexColor("lightblue","#7bc8f6")
        p:indexColor("purply_pink","#f075e6")
        p:indexColor("off_green","#6ba353")
        p:indexColor("ocher","#bf9b0c")
        p:indexColor("milk_chocolate","#7f4e1e")
        p:indexColor("light_peach","#ffd8b1")
        p:indexColor("deep_magenta","#a0025c")
        p:indexColor("caramel","#af6f09")
        p:indexColor("greenish_teal","#32bf84")
        p:indexColor("pale_lime","#befd73")
        p:indexColor("purple_red","#990147")
        p:indexColor("blueberry","#464196")
        p:indexColor("asparagus","#77ab56")
        p:indexColor("pale_grey","#fdfdfe")
        p:indexColor("light_grey_blue","#9dbcd4")
        p:indexColor("pale_lime_green","#b1ff65")
        p:indexColor("grassy_green","#419c03")
        p:indexColor("mossy_green","#638b27")
        p:indexColor("earth","#a2653e")
        p:indexColor("deep_orange","#dc4d01")
        p:indexColor("pale_aqua","#b8ffeb")
        p:indexColor("rose_red","#be013c")
        p:indexColor("stone","#ada587")
        p:indexColor("rusty_orange","#cd5909")
        p:indexColor("pea","#a4bf20")
        p:indexColor("sick_green","#9db92c")
        p:indexColor("darker_pink","#c4387f")
        p:indexColor("chestnut","#742802")
        p:indexColor("blue/green","#0f9b8e")
        p:indexColor("amethyst","#9b5fc0")
        p:indexColor("dark_mint_green","#20c073")
        p:indexColor("pale_rose","#fdc1c5")
        p:indexColor("muted_blue","#3b719f")
        p:indexColor("fawn","#cfaf7b")
        p:indexColor("buff","#fef69e")
        p:indexColor("turquoise_green","#04f489")
        p:indexColor("muddy_brown","#886806")
        p:indexColor("sea","#3c9992")
        p:indexColor("tomato","#ef4026")
        p:indexColor("carnation_pink","#ff7fa7")
        p:indexColor("banana","#ffff7e")
        p:indexColor("neon_yellow","#cfff04")
        p:indexColor("greyish","#a8a495")
        p:indexColor("mid_green","#50a747")
        p:indexColor("muted_purple","#805b87")
        p:indexColor("electric_pink","#ff0490")
        p:indexColor("sandy","#f1da7a")
        p:indexColor("ugly_pink","#cd7584")
        p:indexColor("turquoise_blue","#06b1c4")
        p:indexColor("light_burgundy","#a8415b")
        p:indexColor("greenish_tan","#bccb7a")
        p:indexColor("dark_mint","#48c072")
        p:indexColor("light_urple","#b36ff6")
        p:indexColor("midnight_purple","#280137")
        p:indexColor("pinkish_orange","#ff724c")
        p:indexColor("pear","#cbf85f")
        p:indexColor("dark_plum","#3f012c")
        p:indexColor("tealish","#24bca8")
        p:indexColor("perrywinkle","#8f8ce7")
        p:indexColor("yellowish_orange","#ffab0f")
        p:indexColor("pastel_orange","#ff964f")
        p:indexColor("iris","#6258c4")
        p:indexColor("ultramarine_blue","#1805db")
        p:indexColor("navy_green","#35530a")
        p:indexColor("seaweed","#18d17b")
        p:indexColor("kiwi","#9cef43")
        p:indexColor("fluro_green","#0aff02")
        p:indexColor("bright_light_green","#2dfe54")
        p:indexColor("vivid_green","#2fef10")
        p:indexColor("frog_green","#58bc08")
        p:indexColor("dull_brown","#876e4b")
        p:indexColor("dusk","#4e5481")
        p:indexColor("mustard_brown","#ac7e04")
        p:indexColor("leafy_green","#51b73b")
        p:indexColor("cool_blue","#4984b8")
        p:indexColor("almost_black","#070d0d")
        p:indexColor("yellow/green","#c8fd3d")
        p:indexColor("heliotrope","#d94ff5")
        p:indexColor("green_apple","#5edc1f")
        p:indexColor("baby_poop_green","#8f9805")
        p:indexColor("apple","#6ecb3c")
        p:indexColor("purpleish_pink","#df4ec8")
        p:indexColor("night_blue","#040348")
        p:indexColor("merlot","#730039")
        p:indexColor("lightgreen","#76ff7b")
        p:indexColor("tomato_red","#ec2d01")
        p:indexColor("key_lime","#aeff6e")
        p:indexColor("pale_cyan","#b7fffa")
        p:indexColor("vomit_yellow","#c7c10c")
        p:indexColor("purplish_brown","#6b4247")
        p:indexColor("bubblegum","#ff6cb5")
        p:indexColor("shamrock","#01b44c")
        p:indexColor("mango","#ffa62b")
        p:indexColor("lime_yellow","#d0fe1d")
        p:indexColor("hot_green","#25ff29")
        p:indexColor("grape_purple","#5d1451")
        p:indexColor("faded_orange","#f0944d")
        p:indexColor("avocado_green","#87a922")
        p:indexColor("peacock_blue","#016795")
        p:indexColor("weird_green","#3ae57f")
        p:indexColor("bright_lilac","#c95efb")
        p:indexColor("fern_green","#548d44")
        p:indexColor("dirty_blue","#3f829d")
        p:indexColor("rust_orange","#c45508")
        p:indexColor("heather","#a484ac")
        p:indexColor("deep_teal","#00555a")
        p:indexColor("dark_seafoam","#1fb57a")
        p:indexColor("baby_poo","#ab9004")
        p:indexColor("yellowgreen","#bbf90f")
        p:indexColor("light_sage","#bcecac")
        p:indexColor("light_aquamarine","#7bfdc7")
        p:indexColor("spearmint","#1ef876")
        p:indexColor("bright_lime","#87fd05")
        p:indexColor("vibrant_green","#0add08")
        p:indexColor("very_pale_green","#cffdbc")
        p:indexColor("faded_yellow","#feff7f")
        p:indexColor("bile","#b5c306")
        p:indexColor("viridian","#1e9167")
        p:indexColor("very_light_pink","#fff4f2")
        p:indexColor("puke_brown","#947706")
        p:indexColor("medium_pink","#f36196")
        p:indexColor("ugly_purple","#a442a0")
        p:indexColor("sunshine_yellow","#fffd37")
        p:indexColor("seaweed_green","#35ad6b")
        p:indexColor("light_periwinkle","#c1c6fc")
        p:indexColor("lemon_green","#adf802")
        p:indexColor("greeny_brown","#696006")
        p:indexColor("dark_grey_blue","#29465b")
        p:indexColor("bright_olive","#9cbb04")
        p:indexColor("turtle_green","#75b84f")
        p:indexColor("pale_sky_blue","#bdf6fe")
        p:indexColor("light_mustard","#f7d560")
        p:indexColor("diarrhea","#9f8303")
        p:indexColor("dark_aquamarine","#017371")
        p:indexColor("brownish_pink","#c27e79")
        p:indexColor("baby_shit_green","#889717")
        p:indexColor("purpley","#8756e4")
        p:indexColor("greyblue","#77a1b5")
        p:indexColor("hot_magenta","#f504c9")
        p:indexColor("blue/grey","#758da3")
        p:indexColor("pale","#fff9d0")
        p:indexColor("cool_green","#33b864")
        p:indexColor("sandy_yellow","#fdee73")
        p:indexColor("eggshell_blue","#c4fff7")
        p:indexColor("barf_green","#94ac02")
        p:indexColor("baby_green","#8cff9e")
        p:indexColor("vibrant_purple","#ad03de")
        p:indexColor("brown_grey","#8d8468")
        p:indexColor("water_blue","#0e87cc")
        p:indexColor("lipstick_red","#c0022f")
        p:indexColor("banana_yellow","#fafe4b")
        p:indexColor("wisteria","#a87dc2")
        p:indexColor("purple_brown","#673a3f")
        p:indexColor("brown_yellow","#b29705")
        p:indexColor("purple/pink","#d725de")
        p:indexColor("lemon_lime","#bffe28")
        p:indexColor("grey/blue","#647d8e")
        p:indexColor("dusty_red","#b9484e")
        p:indexColor("deep_rose","#c74767")
        p:indexColor("dark_seafoam_green","#3eaf76")
        p:indexColor("muddy_yellow","#bfac05")
        p:indexColor("carnation","#fd798f")
        p:indexColor("yellowy_brown","#ae8b0c")
        p:indexColor("violet_red","#a50055")
        p:indexColor("twilight_blue","#0a437a")
        p:indexColor("pure_blue","#0203e2")
        p:indexColor("lightish_red","#fe2f4a")
        p:indexColor("brick_orange","#c14a09")
        p:indexColor("velvet","#750851")
        p:indexColor("sunflower","#ffc512")
        p:indexColor("light_mint_green","#a6fbb2")
        p:indexColor("light_grass_green","#9af764")
        p:indexColor("lavender_blue","#8b88f8")
        p:indexColor("rusty_red","#af2f0d")
        p:indexColor("lightish_purple","#a552e6")
        p:indexColor("dried_blood","#4b0101")
        p:indexColor("light_blue_grey","#b7c9e2")
        p:indexColor("leaf","#71aa34")
        p:indexColor("orangish","#fc824a")
        p:indexColor("pale_olive_green","#b1d27b")
        p:indexColor("off_yellow","#f1f33f")
        p:indexColor("dusty_orange","#f0833a")
        p:indexColor("butter","#ffff81")
        p:indexColor("royal","#0c1793")
        p:indexColor("petrol","#005f6a")
        p:indexColor("greenish_cyan","#2afeb7")
        p:indexColor("duck_egg_blue","#c3fbf4")
        p:indexColor("bubble_gum_pink","#ff69af")
        p:indexColor("bluegrey","#85a3b2")
        p:indexColor("warm_brown","#964e02")
        p:indexColor("twilight","#4e518b")
        p:indexColor("saffron","#feb209")
        p:indexColor("purple/blue","#5d21d0")
        p:indexColor("dark_sand","#a88f59")
        p:indexColor("vibrant_blue","#0339f8")
        p:indexColor("putty","#beae8a")
        p:indexColor("lawn_green","#4da409")
        p:indexColor("camouflage_green","#4b6113")
        p:indexColor("blush_pink","#fe828c")
        p:indexColor("reddy_brown","#6e1005")
        p:indexColor("darkish_red","#a90308")
        p:indexColor("algae_green","#21c36f")
        p:indexColor("dark_coral","#cf524e")
        p:indexColor("bright_cyan","#41fdfe")
        p:indexColor("piss_yellow","#ddd618")
        p:indexColor("pastel_red","#db5856")
        p:indexColor("greenish_turquoise","#00fbb0")
        p:indexColor("dark","#1b2431")
        p:indexColor("ruby","#ca0147")
        p:indexColor("poop_green","#6f7c00")
        p:indexColor("orangered","#fe420f")
        p:indexColor("dandelion","#fedf08")
        p:indexColor("claret","#680018")
        p:indexColor("pale_mauve","#fed0fc")
        p:indexColor("lipstick","#d5174e")
        p:indexColor("rosa","#fe86a4")
        p:indexColor("darkblue","#030764")
        p:indexColor("tan_brown","#ab7e4c")
        p:indexColor("shit_green","#758000")
        p:indexColor("red_wine","#8c0034")
        p:indexColor("pinky","#fc86aa")
        p:indexColor("mud_green","#606602")
        p:indexColor("light_greenish_blue","#63f7b4")
        p:indexColor("dull_teal","#5f9e8f")
        p:indexColor("deep_lavender","#8d5eb7")
        p:indexColor("vivid_blue","#152eff")
        p:indexColor("raw_umber","#a75e09")
        p:indexColor("light_mint","#b6ffbb")
        p:indexColor("light_light_blue","#cafffb")
        p:indexColor("highlighter_green","#1bfc06")
        p:indexColor("greeny_grey","#7ea07a")
        p:indexColor("bluey_grey","#89a0b0")
        p:indexColor("algae","#54ac68")
        p:indexColor("sap_green","#5c8b15")
        p:indexColor("pale_salmon","#ffb19a")
        p:indexColor("metallic_blue","#4f738e")
        p:indexColor("ice","#d6fffa")
        p:indexColor("gross_green","#a0bf16")
        p:indexColor("dodger_blue","#3e82fc")
        p:indexColor("warm_pink","#fb5581")
        p:indexColor("light_green_blue","#56fca2")
        p:indexColor("flat_green","#699d4c")
        p:indexColor("dark_blue_grey","#1f3b4d")
        p:indexColor("clay_brown","#b2713d")
        p:indexColor("sand_yellow","#fce166")
        p:indexColor("grapefruit","#fd5956")
        p:indexColor("blood_orange","#fe4b03")
        p:indexColor("very_pale_blue","#d6fffe")
        p:indexColor("old_pink","#c77986")
        p:indexColor("neon_red","#ff073a")
        p:indexColor("golden_rod","#f9bc08")
        p:indexColor("plum_purple","#4e0550")
        p:indexColor("pale_peach","#ffe5ad")
        p:indexColor("green_again","#16d43f")
        p:indexColor("dark_yellow_green","#728f02")
        p:indexColor("carmine","#9d0216")
        p:indexColor("deep_sea_blue","#015482")
        p:indexColor("dark_hot_pink","#d90166")
        p:indexColor("warm_blue","#4b57db")
        p:indexColor("light_khaki","#e6f2a2")
        p:indexColor("icky_green","#8fae22")
        p:indexColor("greenblue","#23c48b")
        p:indexColor("dirty_purple","#734a65")
        p:indexColor("rich_blue","#021bf9")
        p:indexColor("mushroom","#ba9e88")
        p:indexColor("flat_blue","#3c73a8")
        p:indexColor("dark_slate_blue","#214761")
        p:indexColor("dark_sage","#598556")
        p:indexColor("coral_pink","#ff6163")
        p:indexColor("true_green","#089404")
        p:indexColor("darkish_purple","#751973")
        p:indexColor("dark_taupe","#7f684e")
        p:indexColor("cool_grey","#95a3a6")
        p:indexColor("canary","#fdff63")
        p:indexColor("booger_green","#96b403")
        p:indexColor("muted_pink","#d1768f")
        p:indexColor("hazel","#8e7618")
        p:indexColor("dark_royal_blue","#02066f")
        p:indexColor("vivid_purple","#9900fa")
        p:indexColor("racing_green","#014600")
        p:indexColor("leather","#ac7434")
        p:indexColor("green/blue","#01c08d")
        p:indexColor("sunflower_yellow","#ffda03")
        p:indexColor("rich_purple","#720058")
        p:indexColor("pale_magenta","#d767ad")
        p:indexColor("light_yellowish_green","#c2ff89")
        p:indexColor("indigo_blue","#3a18b1")
        p:indexColor("dark_fuchsia","#9d0759")
        p:indexColor("yellow_tan","#ffe36e")
        p:indexColor("wintergreen","#20f986")
        p:indexColor("violet_pink","#fb5ffc")
        p:indexColor("topaz","#13bbaf")
        p:indexColor("seafoam_blue","#78d1b6")
        p:indexColor("light_gold","#fddc5c")
        p:indexColor("grey/green","#86a17d")
        p:indexColor("foam_green","#90fda9")
        p:indexColor("creme","#ffffb6")
        p:indexColor("clear_blue","#247afd")
        p:indexColor("ugly_blue","#31668a")
        p:indexColor("terracota","#cb6843")
        p:indexColor("very_dark_brown","#1d0200")
        p:indexColor("straw","#fcf679")
        p:indexColor("parchment","#fefcaf")
        p:indexColor("orangey_yellow","#fdb915")
        p:indexColor("greyish_teal","#719f91")
        p:indexColor("sapphire","#2138ab")
        p:indexColor("nice_blue","#107ab0")
        p:indexColor("browny_orange","#ca6b02")
        p:indexColor("washed_out_green","#bcf5a6")
        p:indexColor("tiffany_blue","#7bf2da")
        p:indexColor("light_seafoam","#a0febf")
        p:indexColor("light_neon_green","#4efd54")
        p:indexColor("light_bright_green","#53fe5c")
        p:indexColor("light_bluish_green","#76fda8")
        p:indexColor("rosy_pink","#f6688e")
        p:indexColor("peachy_pink","#ff9a8a")
        p:indexColor("pale_light_green","#b1fc99")
        p:indexColor("old_rose","#c87f89")
        p:indexColor("fern","#63a950")
        p:indexColor("dusk_blue","#26538d")
        p:indexColor("camo","#7f8f4e")
        p:indexColor("burnt_siena","#b75203")
        p:indexColor("tealish_green","#0cdc73")
        p:indexColor("swamp","#698339")
        p:indexColor("sand_brown","#cba560")
        p:indexColor("rust_brown","#8b3103")
        p:indexColor("orangeish","#fd8d49")
        p:indexColor("light_royal_blue","#3a2efe")
        p:indexColor("cocoa","#875f42")
        p:indexColor("baby_purple","#ca9bf7")
        p:indexColor("raw_sienna","#9a6200")
        p:indexColor("radioactive_green","#2cfa1f")
        p:indexColor("light_pea_green","#c4fe82")
        p:indexColor("cinnamon","#ac4f06")
        p:indexColor("squash","#f2ab15")
        p:indexColor("charcoal_grey","#3c4142")
        p:indexColor("bright_yellow_green","#9dff00")
        p:indexColor("baby_puke_green","#b6c406")
        p:indexColor("poison_green","#40fd14")
        p:indexColor("light_lavendar","#efc0fe")
        p:indexColor("indian_red","#850e04")
        p:indexColor("dark_cream","#fff39a")
        p:indexColor("toupe","#c7ac7d")
        p:indexColor("butterscotch","#fdb147")
        p:indexColor("burple","#6832e3")
        p:indexColor("tan_green","#a9be70")
        p:indexColor("sun_yellow","#ffdf22")
        p:indexColor("pale_gold","#fdde6c")
        p:indexColor("light_light_green","#c8ffb0")
        p:indexColor("lichen","#8fb67b")
        p:indexColor("green/yellow","#b5ce08")
        p:indexColor("darkgreen","#054907")
        p:indexColor("azul","#1d5dec")
        p:indexColor("sunny_yellow","#fff917")
        p:indexColor("sickly_yellow","#d0e429")
        p:indexColor("kelley_green","#009337")
        p:indexColor("bruise","#7e4071")
        p:indexColor("browny_green","#6f6c0a")
        p:indexColor("battleship_grey","#6b7c85")
        p:indexColor("off_blue","#5684ae")
        p:indexColor("manilla","#fffa86")
        p:indexColor("greenish_beige","#c9d179")
        p:indexColor("deep_brown","#410200")
        p:indexColor("darkish_pink","#da467d")
        p:indexColor("custard","#fffd78")
        p:indexColor("ugly_brown","#7d7103")
        p:indexColor("stormy_blue","#507b9c")
        p:indexColor("liliac","#c48efd")
        p:indexColor("baby_shit_brown","#ad900d")
        p:indexColor("reddish_grey","#997570")
        p:indexColor("powder_pink","#ffb2d0")
        p:indexColor("eggplant_purple","#430541")
        p:indexColor("egg_shell","#fffcc4")
        p:indexColor("very_light_brown","#d3b683")
        p:indexColor("tea_green","#bdf8a3")
        p:indexColor("orange_pink","#ff6f52")
        p:indexColor("light_grey_green","#b7e1a1")
        p:indexColor("kiwi_green","#8ee53f")
        p:indexColor("boring_green","#63b365")
        p:indexColor("light_pastel_green","#b2fba5")
        p:indexColor("candy_pink","#ff63e9")
        p:indexColor("purply","#983fb2")
        p:indexColor("purpley_grey","#947e94")
        p:indexColor("dusty_lavender","#ac86a8")
        p:indexColor("desert","#ccad60")
        p:indexColor("deep_lilac","#966ebd")
        p:indexColor("pig_pink","#e78ea5")
        p:indexColor("olive_yellow","#c2b709")
        p:indexColor("light_seafoam_green","#a7ffb5")
        p:indexColor("light_moss_green","#a6c875")
        p:indexColor("lavender_pink","#dd85d7")
        p:indexColor("deep_aqua","#08787f")
        p:indexColor("bland","#afa88b")
        p:indexColor("strong_pink","#ff0789")
        p:indexColor("green_teal","#0cb577")
        p:indexColor("deep_turquoise","#017374")
        p:indexColor("dark_green_blue","#1f6357")
        p:indexColor("bright_sea_green","#05ffa6")
        p:indexColor("booger","#9bb53c")
        p:indexColor("blue_with_a_hint_of_purple","#533cc6")
        p:indexColor("blue_blue","#2242c7")
        p:indexColor("windows_blue","#3778bf")
        p:indexColor("toxic_green","#61de2a")
        p:indexColor("strong_blue","#0c06f7")
        p:indexColor("spruce","#0a5f38")
        p:indexColor("pinkish_tan","#d99b82")
        p:indexColor("macaroni_and_cheese","#efb435")
        p:indexColor("grey_teal","#5e9b8a")
        p:indexColor("dusty_teal","#4c9085")
        p:indexColor("dark_grass_green","#388004")
        p:indexColor("cement","#a5a391")
        p:indexColor("yellowish_tan","#fcfc81")
        p:indexColor("warm_purple","#952e8f")
        p:indexColor("tea","#65ab7c")
        p:indexColor("really_light_blue","#d4ffff")
        p:indexColor("nasty_green","#70b23f")
        p:indexColor("light_eggplant","#894585")
        p:indexColor("fresh_green","#69d84f")
        p:indexColor("electric_lime","#a8ff04")
        p:indexColor("dust","#b2996e")
        p:indexColor("dark_pastel_green","#56ae57")
        p:indexColor("cloudy_blue","#acc2d9")
        p:indexColor("highlighter_blue","#30C5FF")
        for i=0,255 do
            p:indexColor("gray"..i,i,i,i)
        end
    end
	return p
end

return color